name: Dispatch event to Rotate Product Configuration

on:
  workflow_dispatch:  
  push:
    branches:
      - main
    tags:
      # Simple pattern for version tags (includes prerelease and build metadata)
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  rotate-config:
    name: Rotate product config
    permissions:
      actions: write
      contents: read 
    secrets:
      # Finer-grained PAT needs {contents:read,actions:write} in both prodcut-repo and this repo
      token: ${{ secrets.PRODUCT_ROTATOR_TOKEN }} 
    uses: thetechcollective/gh-rotator/.github/workflows/dispatch.yml@stable
    with:
      product-repo: Arla-OMB/omb-product
      # product-workflow defautl is .github/workflows/rotator.yml
      # product-workflow: .github/workflows/rotator.yml 
      # prodcut-branch default is main
      # product-branch: main 